const fs = require("fs");
const path = require("path");

const root = __dirname;

const jsModules = [
    ["main", "js/plugin-entry.js"],
    ["js/plugin-lifecycle", "js/plugin-lifecycle.js"],
    ["js/plugin-settings", "js/plugin-settings.js"],
    ["js/plugin-minimap-manager", "js/plugin-minimap-manager.js"],
    ["js/plugin-helper-leaves", "js/plugin-helper-leaves.js"],
    ["js/settings-tab", "js/settings-tab.js"],
    ["js/minimap", "js/minimap.js"],
    ["js/minimap-settings", "js/minimap-settings.js"],
    ["js/minimap-layout", "js/minimap-layout.js"],
    ["js/minimap-rendering", "js/minimap-rendering.js"],
    ["js/minimap-scroll", "js/minimap-scroll.js"],
    ["js/renderers", "js/renderers.js"],
    ["js/utils", "js/utils.js"],
];

const cssFiles = [
    "styles/minimap-frame.css",
    "styles/minimap-slider.css",
    "styles/minimap-layout.css",
    "styles/minimap-disabled.css",
];

function read(file) {
    return fs.readFileSync(path.join(root, file), "utf8").replace(/\r\n/g, "\n");
}

function buildMain() {
    const modules = jsModules
        .map(([id, file]) => {
            const code = read(file);
            return `${JSON.stringify(id)}: function(require, module, exports) {\n${code}\n}`;
        })
        .join(",\n");

    const bundled = `// Generated by build.js from files in js/. Edit js/*, then run: node build.js\n` +
        `const __nativeRequire = require;\n` +
        `const __modules = {\n${modules}\n};\n` +
        `const __cache = Object.create(null);\n` +
        `function __normalize(id) {\n` +
        `    const parts = [];\n` +
        `    for (const part of id.split("/")) {\n` +
        `        if (!part || part === ".") continue;\n` +
        `        if (part === "..") parts.pop();\n` +
        `        else parts.push(part);\n` +
        `    }\n` +
        `    return parts.join("/").replace(/\\.js$/, "");\n` +
        `}\n` +
        `function __dirnameOf(id) {\n` +
        `    const slash = id.lastIndexOf("/");\n` +
        `    return slash === -1 ? "" : id.slice(0, slash);\n` +
        `}\n` +
        `function __resolve(request, parentId) {\n` +
        `    if (!request.startsWith(".")) return request;\n` +
        `    return __normalize(__dirnameOf(parentId) + "/" + request);\n` +
        `}\n` +
        `function __require(request, parentId) {\n` +
        `    const id = __resolve(request, parentId || "main");\n` +
        `    if (!__modules[id]) return __nativeRequire(request);\n` +
        `    if (__cache[id]) return __cache[id].exports;\n` +
        `    const module = { exports: {} };\n` +
        `    __cache[id] = module;\n` +
        `    const localRequire = (nextRequest) => __require(nextRequest, id);\n` +
        `    __modules[id](localRequire, module, module.exports);\n` +
        `    return module.exports;\n` +
        `}\n` +
        `module.exports = __require("./main", "main");\n`;

    fs.writeFileSync(path.join(root, "main.js"), bundled);
}

function buildStyles() {
    const styles = cssFiles
        .map((file) => `/* ${file} */\n${read(file).trim()}\n`)
        .join("\n");
    fs.writeFileSync(
        path.join(root, "styles.css"),
        `/* Generated by build.js from files in styles/. Edit styles/*, then run: node build.js */\n${styles}`
    );
}

buildMain();
buildStyles();
