// Generated by build.js from files in js/. Edit js/*, then run: node build.js
const __nativeRequire = require;
const __modules = {
"main": function(require, module, exports) {
const { Plugin } = require("obsidian");

const lifecycleMethods = require("./js/plugin-lifecycle");
const settingsMethods = require("./js/plugin-settings");
const minimapManagerMethods = require("./js/plugin-minimap-manager");
const helperLeafMethods = require("./js/plugin-helper-leaves");

class NoteMinimap extends Plugin {
    activeNoteView = null;
    updateNeeded = false;
    minimapInstances = new Map();
    stylesHTMLCache = null;
    cssVarsCache = null;
    helperLeafIds = new Map();
}

Object.assign(
    NoteMinimap.prototype,
    lifecycleMethods,
    settingsMethods,
    minimapManagerMethods,
    helperLeafMethods
);

module.exports = NoteMinimap;

},
"js/plugin-lifecycle": function(require, module, exports) {
const { MarkdownView, debounce } = require("obsidian");
const MinimapSettingTab = require("./settings-tab");
const { throttle } = require("./utils");

module.exports = {
    async onload() {
        console.log("NoteMinimap Loaded");

        const resized = new Set();
        const resize = throttle(() => {
            for (const el of resized) {
                for (const [element, note] of this.minimapInstances.entries()) {
                    if (element === el) {
                        note.onResize();
                        break;
                    }
                }
            }
            resized.clear();
        }, 1000);

        this.resizeObserver = new ResizeObserver((entries) => {
            for (const entry of entries) resized.add(entry.target);
            resize();
        });

        this.modeObserver = new MutationObserver((entries) => {
            const entry = entries[0];
            const noteInstance = this.minimapInstances.get(
                entry.target.parentElement
            );
            if (entry.attributeName === "style") noteInstance?.modeChange();
            this.updateElementMinimap();
        });

        this.registerEvent(
            this.app.workspace.on("active-leaf-change", (newActiveLeaf) => {
                if (!newActiveLeaf?.view) return;
                this.checkAndDealWithUserOpeningHelperLeaves(newActiveLeaf);
                this.updateElementMinimap();
                this.activeNoteView = newActiveLeaf.view;
                this.updateElementMinimap();

                if (newActiveLeaf?.view?.getViewType() === "markdown") {
                    if (this.settings.betterRendering) this.openHelperForLeaf(newActiveLeaf);
                    this.addToggleButtonToLeaf(newActiveLeaf);
                }
            })
        );

        this.debouncedUpdateMinimap = debounce(
            () => this.updateElementMinimap(),
            700,
            false
        );
        this.registerEvent(
            this.app.workspace.on("editor-change", this.debouncedUpdateMinimap)
        );
        this.registerDomEvent(document, "click", (event) => {
            const target = event.target;
            if (!(target instanceof Element)) return;
            if (
                target.closest(
                    ".callout-title, .collapse-indicator, .task-kanban-inline-action"
                )
            ) {
                window.setTimeout(() => this.updateElementMinimap(), 120);
            }
        }, true);

        const updateHelpers = throttle(() => {
            this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
                this.updateHelperForLeaf(leaf);
            });
            this.updateElementMinimap();
        }, 500);

        this.registerLayoutChangeHandler(updateHelpers);

        await this.loadSettings();
        this.addSettingTab(new MinimapSettingTab(this));
        this.app.workspace.onLayoutReady(() => {
            this.activeNoteView =
                this.app.workspace.getActiveViewOfType(MarkdownView);
            this.injectMinimapIntoAllNotes();
        });
    },

    registerLayoutChangeHandler(updateHelpers) {
        this.registerEvent(
            this.app.workspace.on("layout-change", () => {
                if (this.settings.betterRendering) {
                    this.detachRedundantHelperLeavesAndRestoreMissing();
                    updateHelpers();
                }

                this.minimapInstances
                    .get(this.activeNoteView?.contentEl)
                    ?.onResize();

                const openEls = new Set(
                    this.app.workspace
                        .getLeavesOfType("markdown")
                        .map((leaf) => leaf.view.contentEl)
                );
                for (const [el, note] of this.minimapInstances.entries()) {
                    if (!openEls.has(el)) {
                        note.destroy();
                        this.minimapInstances.delete(el);
                        this.resizeObserver.unobserve(el);
                    }
                }
            })
        );
    },

    onunload() {
        if (this.debouncedUpdateMinimap?.cancel) {
            this.debouncedUpdateMinimap.cancel();
        }

        this.minimapInstances.forEach((noteInstance) => noteInstance.destroy());
        this.resizeObserver.disconnect();
        this.modeObserver.disconnect();

        document
            .querySelectorAll(".minimap-toggle-button")
            .forEach((button) => button.remove());
        this.detachAllHelperLeaves();

        console.log("NoteMinimap Unloaded");
    },
};

},
"js/plugin-settings": function(require, module, exports) {
module.exports = {
    async loadSettings() {
        this.settings = Object.assign(
            {
                enabledByDefault: true,
                betterRendering: true,
                scale: 0.12,
                minimapOpacity: 0.3,
                sliderOpacity: 0.3,
                topOffset: 0,
            },
            await this.loadData()
        );

        if (!Number.isFinite(this.settings.scale)) {
            this.settings.scale = 0.12;
        }
    },

    async saveSettings() {
        await this.saveData(this.settings);

        for (const note of this.minimapInstances.values()) {
            note.updateSettings(this.settings);
        }
    },

    getStylesHTML() {
        if (this.stylesHTMLCache) return this.stylesHTMLCache;

        const styleElements = Array.from(
            document.head.querySelectorAll('style, link[rel="stylesheet"]')
        );
        this.stylesHTMLCache = styleElements.map((el) => el.outerHTML).join("\n");
        return this.stylesHTMLCache;
    },

    getCssVars() {
        if (this.cssVarsCache) return this.cssVarsCache;

        const rootStyles = getComputedStyle(document.body);
        let cssVars = ":root {\n";
        for (let i = 0; i < rootStyles.length; i++) {
            const prop = rootStyles[i];
            if (prop.startsWith("--")) {
                cssVars += `  ${prop}: ${rootStyles.getPropertyValue(prop)};\n`;
            }
        }
        cssVars += "}\n::-webkit-scrollbar { display: none; }";
        this.cssVarsCache = cssVars;
        return cssVars;
    },
};

},
"js/plugin-minimap-manager": function(require, module, exports) {
const { setIcon } = require("obsidian");
const Minimap = require("./minimap");
const { sleep } = require("./utils");

module.exports = {
    injectMinimapIntoAllNotes() {
        const leaves = this.app.workspace.getLeavesOfType("markdown");
        for (const leaf of leaves) {
            if (this.settings.betterRendering) this.openHelperForLeaf(leaf);
            this.addToggleButtonToLeaf(leaf);
            this.updateElementMinimap(
                leaf.view.contentEl,
                this.helperLeafIds.get(leaf.id)
            );
        }
    },

    async updateElementMinimap(element, helperLeafId) {
        await sleep(100);
        const activeLeaf = this.app.workspace.activeLeaf;
        helperLeafId = activeLeaf
            ? this.helperLeafIds.get(activeLeaf.id)
            : helperLeafId;

        if (!element) {
            if (!this.activeNoteView) return;
            element = this.activeNoteView.contentEl;
        }

        if (
            !element.querySelector(".markdown-source-view") ||
            !element.querySelector(".markdown-preview-view")
        ) {
            return;
        }

        const existing = this.minimapInstances.get(element);
        const isReadMode =
            element.querySelector(".markdown-source-view")?.clientHeight === 0;

        if (!isReadMode) {
            if (existing) {
                existing.destroy();
                this.minimapInstances.delete(element);
                this.resizeObserver.unobserve(element);
            }
            return;
        }

        if (element.classList.contains("minimap-disabled")) {
            if (existing) {
                existing.destroy();
                this.minimapInstances.delete(element);
                this.resizeObserver.unobserve(element);
            }
            return;
        }

        if (this.minimapInstances.has(element)) {
            const noteInstance = this.minimapInstances.get(element);
            noteInstance.updateIframe();
        } else {
            const minimapInstance = new Minimap(
                this,
                element,
                this.settings,
                helperLeafId
            );
            this.minimapInstances.set(element, minimapInstance);
            this.resizeObserver.observe(element);
            this.modeObserver.observe(minimapInstance.sourceView, {
                attributes: true,
            });
        }
    },

    addToggleButtonToLeaf(leaf) {
        const viewActions = leaf.view.containerEl.querySelector(".view-actions");
        if (!viewActions) return;
        if (viewActions.querySelector(".minimap-toggle-button")) return;

        const button = document.createElement("button");
        button.className = "clickable-icon view-actions minimap-toggle-button";
        button.setAttribute("aria-label", "Toggle Minimap");
        setIcon(button, "star-list");

        const contentEl = leaf.view.contentEl;
        button.onclick = () => {
            contentEl.classList.toggle("minimap-disabled");
            this.updateElementMinimap(contentEl);
        };

        if (!this.settings.enabledByDefault) {
            contentEl.classList.add("minimap-disabled");
        }

        viewActions.prepend(button);
    },
};

},
"js/plugin-helper-leaves": function(require, module, exports) {
const { Notice } = require("obsidian");
const { sleep } = require("./utils");

module.exports = {
    async openHelperForLeaf(leaf) {
        if (!leaf) return;
        if (this.helperLeafIds.has(leaf.id)) return;
        if ([...this.helperLeafIds.values()].includes(leaf.id)) return;

        const file = leaf.view.file;
        if (!file) return;

        const rightLeaf = this.app.workspace.getRightLeaf(false);
        this.helperLeafIds.set(leaf.id, rightLeaf.id);
        this.updateHelperForLeaf(leaf);
    },

    detachRedundantHelperLeavesAndRestoreMissing() {
        this.helperLeafIds.forEach((helperLeafId, originalLeafId) => {
            if (this.app.workspace.getLeafById(originalLeafId)) {
                if (!this.app.workspace.getLeafById(helperLeafId)) {
                    this.helperLeafIds.delete(originalLeafId);
                    const originalLeaf =
                        this.app.workspace.getLeafById(originalLeafId);
                    this.openHelperForLeaf(originalLeaf);
                    new Notice(
                        "Note Minimap: This is a helper note used for Better Rendering - avoid touching it!",
                        4000
                    );
                }
            } else {
                const helperLeaf = this.app.workspace.getLeafById(helperLeafId);
                if (helperLeaf) helperLeaf.detach();
                this.helperLeafIds.delete(originalLeafId);
            }
        });
    },

    checkAndDealWithUserOpeningHelperLeaves(newActiveLeaf) {
        if (
            newActiveLeaf?.id &&
            [...this.helperLeafIds.values()].includes(newActiveLeaf.id)
        ) {
            newActiveLeaf.detach();
        }
    },

    detachAllHelperLeaves() {
        this.helperLeafIds.forEach((helperLeafId) => {
            this.app.workspace.getLeafById(helperLeafId)?.detach();
        });
    },

    async updateHelperForLeaf(leaf) {
        const helperLeaf = this.app.workspace.getLeafById(
            this.helperLeafIds.get(leaf?.id)
        );
        if (!helperLeaf) return;

        const oldState = helperLeaf.view.getState();
        const newState = leaf.view.getState();
        await helperLeaf.setViewState({
            type: "markdown",
            state: newState,
        });
        if (oldState.file !== newState.file) {
            await this.initialForceloadContentInMarkdownView(helperLeaf.view);
        }
    },

    async initialForceloadContentInMarkdownView(view) {
        if (view?.getViewType() !== "markdown") return;
        view.contentEl
            .querySelectorAll(".markdown-preview-sizer, .cm-sizer")
            .forEach((el) => {
                el.style = "transform-origin: top right; scale: .1;";
            });
        const data = await view.getViewData();
        await view.clear();
        await sleep(100);
        await view.setViewData(data);
    },
};

},
"js/settings-tab": function(require, module, exports) {
const { Notice, PluginSettingTab, Setting } = require("obsidian");

class MinimapSettingTab extends PluginSettingTab {
    constructor(plugin) {
        super(plugin.app, plugin);
        this.plugin = plugin;
    }

    display() {
        const { containerEl } = this;
        containerEl.empty();

        new Setting(containerEl)
            .setName("Enable by default")
            .setDesc("Already opened notes will not be affected by changing this")
            .addToggle((toggle) => {
                toggle
                    .setValue(this.plugin.settings.enabledByDefault)
                    .onChange((value) => {
                        this.plugin.settings.enabledByDefault = value;
                        this.plugin.saveSettings();
                    });
            });

        new Setting(containerEl)
            .setName("Better Rendering (in development)")
            .setDesc(
                "Use a hidden helper note to render the minimap, improving flickering and consistent loading. Changing this will trigger a plugin restart"
            )
            .addToggle((toggle) => {
                toggle
                    .setValue(this.plugin.settings.betterRendering)
                    .onChange(async (value) => {
                        this.plugin.settings.betterRendering = value;
                        await this.plugin.saveSettings();

                        await this.app.plugins.disablePlugin("cursor-minimap");
                        await this.app.plugins.enablePlugin("cursor-minimap");
                        this.app.setting.openTabById("cursor-minimap");
                        new Notice(
                            "Note Minimap: Restarted plugin for Better Rendering change.",
                            3000
                        );
                    });
            });

        this.addSliderSetting(
            "Scale",
            "Change the minimap scale (0.05 - 0.3)",
            "scale",
            0.05,
            0.3,
            0.01
        );
        this.addSliderSetting(
            "Opacity",
            "Change the minimap's background opacity (0.05 - 1)",
            "minimapOpacity",
            0.05,
            1,
            0.01
        );
        this.addSliderSetting(
            "Slider Opacity",
            "Change the slider opacity (0.05 - 1)",
            "sliderOpacity",
            0.05,
            1,
            0.01
        );
        this.addSliderSetting(
            "Top Offset",
            "Offset the minimap from the top (pixels) - for special plugin toolbars",
            "topOffset",
            0,
            100,
            1
        );
    }

    addSliderSetting(name, description, key, min, max, step) {
        new Setting(this.containerEl)
            .setName(name)
            .setDesc(description)
            .addSlider((slider) => {
                slider
                    .setLimits(min, max, step)
                    .setValue(this.plugin.settings[key])
                    .setDynamicTooltip()
                    .onChange((value) => {
                        this.plugin.settings[key] = value;
                        this.plugin.saveSettings();
                    });
            });
    }
}

module.exports = MinimapSettingTab;

},
"js/minimap": function(require, module, exports) {
const minimapSettingsMethods = require("./minimap-settings");
const minimapLayoutMethods = require("./minimap-layout");
const minimapRenderingMethods = require("./minimap-rendering");
const minimapScrollMethods = require("./minimap-scroll");

class Minimap {
    minimapScrollOffset = 0;

    constructor(plugin, element, settings, helperLeafId) {
        this.plugin = plugin;
        this.element = element;
        this.helperLeafId = helperLeafId;
        this.helperElement =
            plugin.app.workspace.getLeafById(helperLeafId)?.view?.contentEl;
        this.lastIframeHTML = "";
        this.sourceView = element.querySelector(".markdown-source-view");

        this.updateSliderScroll = this.updateSliderScroll.bind(this);
        this.onSliderMouseDown = this.onSliderMouseDown.bind(this);
        this.onSliderMouseMove = this.onSliderMouseMove.bind(this);
        this.onSliderMouseUp = this.onSliderMouseUp.bind(this);
        this.onMinimapMouseDown = this.onMinimapMouseDown.bind(this);
        this.onMinimapDragMove = this.onMinimapDragMove.bind(this);
        this.onMinimapDragUp = this.onMinimapDragUp.bind(this);
        this.onMinimapWheel = this.onMinimapWheel.bind(this);
        this.onIframeLoad = this.onIframeLoad.bind(this);

        this.modeChange();
        this.setupElements();
        this.updateSettings(settings);

        this.scroller.addEventListener("scroll", this.updateSliderScroll);
        this.slider.addEventListener("mousedown", this.onSliderMouseDown);
        this.container.addEventListener("mousedown", this.onMinimapMouseDown);
        this.container.addEventListener("wheel", this.onMinimapWheel, {
            passive: false,
        });
    }

    destroy() {
        this.scroller.removeEventListener("scroll", this.updateSliderScroll);
        this.slider.removeEventListener("mousedown", this.onSliderMouseDown);
        this.iframe?.removeEventListener("load", this.onIframeLoad);
        this.container.removeEventListener("mousedown", this.onMinimapMouseDown);
        this.container.removeEventListener("wheel", this.onMinimapWheel);
        document.removeEventListener("mousemove", this.onSliderMouseMove);
        document.removeEventListener("mouseup", this.onSliderMouseUp);
        document.removeEventListener("mousemove", this.onMinimapDragMove);
        document.removeEventListener("mouseup", this.onMinimapDragUp);

        this.container.remove();
        this.iframe = null;
        this.slider = null;
        this.container = null;
        this.element.style.removeProperty("--cursor-minimap-reserved");
    }
}

Object.assign(
    Minimap.prototype,
    minimapSettingsMethods,
    minimapLayoutMethods,
    minimapRenderingMethods,
    minimapScrollMethods
);

module.exports = Minimap;

},
"js/minimap-settings": function(require, module, exports) {
const { toRGBAAlpha } = require("./utils");

module.exports = {
    updateSettings(settings) {
        this.scale = settings.scale;
        this.minimapOpacity = settings.minimapOpacity;
        this.sliderOpacity = settings.sliderOpacity;
        this.topOffset = settings.topOffset;

        this.backgroundColor = toRGBAAlpha(
            document
                .querySelector(".view-content")
                .getCssPropertyValue("background-color"),
            this.minimapOpacity
        );

        if (this.iframe && this.slider) {
            this.updateSettingsInCSS();
            this.onResize();
            this.updateIframe();
            this.updateSliderScroll();
        }
    },

    updateSettingsInCSS() {
        if (this.container) {
            this.container.style.setProperty("--scale", this.scale);
            this.container.style.setProperty(
                "--y-scale",
                this.yScale || this.scale
            );
        }
        if (this.slider) this.slider.style.opacity = this.sliderOpacity;
        if (this.iframe) this.iframe.style.top = `${this.topOffset}px`;
        this.updateReservedWidth();
    },
};

},
"js/minimap-layout": function(require, module, exports) {
const { sleep } = require("./utils");

module.exports = {
    isReadModeActive() {
        return this.sourceView.clientHeight === 0;
    },

    modeChange() {
        if (!this.isReadModeActive()) {
            this.plugin.updateElementMinimap(this.element);
            return;
        }

        this.changeScroller(
            this.element.querySelector(
                ".markdown-preview-view"
            )
        );
        this.lastIframeHTML = "";
        this.updateIframe();
    },

    changeScroller(newScroller) {
        if (this.scroller) {
            this.scroller.removeEventListener(
                "scroll",
                this.updateSliderScroll
            );
        }
        this.scroller = newScroller;
        if (this.scroller) {
            this.scroller.addEventListener("scroll", this.updateSliderScroll);
            this.onResize();
        }
    },

    async onResize() {
        await sleep(300);

        const visibleHeight = this.scroller.getBoundingClientRect().height;
        const sizerHeight =
            this.scroller.firstChild?.getBoundingClientRect().height || 0;
        const scrollHeight = this.scroller.scrollHeight || 0;
        this.bottomOverscrollHeight = Math.max(0, scrollHeight - sizerHeight);

        if (!this.hasMeasuredIframeHeight) {
            this.documentHeight = sizerHeight || scrollHeight;
        }
        const fullHeight = this.hasMeasuredIframeHeight
            ? this.documentHeight
            : this.documentHeight + this.bottomOverscrollHeight;
        this.resize(fullHeight, visibleHeight);
    },

    resize(fullHeight, visibleHeight) {
        this.fullHeight = Math.max(1, fullHeight || 1);
        this.visibleHeight = Math.max(1, visibleHeight || 1);
        const availableHeight = Math.max(
            1,
            this.visibleHeight - (this.topOffset || 0)
        );
        this.yScale = Math.min(this.scale, availableHeight / this.fullHeight);
        if (this.container) {
            this.container.style.setProperty("--y-scale", this.yScale);
        }
        this.iframe.style.height = `${fullHeight}px`;
        this.slider.style.height = `${this.visibleHeight * this.yScale}px`;
        this.updateSliderScroll();
    },

    setupElements() {
        this.element
            .querySelectorAll(
                ".minimap-container, .minimap-frame, .minimap-slider"
            )
            .forEach((element) => element.remove());

        this.container = document.createElement("div");
        this.container.className = "minimap-container";
        this.element.prepend(this.container);

        this.iframe = document.createElement("iframe");
        this.iframe.className = "minimap-frame";
        this.iframe.addEventListener("load", this.onIframeLoad);
        this.container.appendChild(this.iframe);

        this.overlay = document.createElement("div");
        this.overlay.className = "minimap-click-overlay";
        this.container.appendChild(this.overlay);

        this.slider = document.createElement("div");
        this.slider.className = "minimap-slider";
        this.container.appendChild(this.slider);
        this.updateReservedWidth();
    },

    updateReservedWidth() {
        if (!this.element || !this.scale) return;
        const width = Math.ceil(this.element.clientWidth * this.scale + 12);
        this.element.style.setProperty("--cursor-minimap-reserved", `${width}px`);
    },
};

},
"js/minimap-rendering": function(require, module, exports) {
const { renderEditMode, renderReadMode } = require("./renderers");

module.exports = {
    async updateIframe(noteContent) {
        if (this.isUpdatingIframe) {
            this.needsIframeUpdate = true;
            return;
        }

        this.isUpdatingIframe = true;

        try {
            if (!noteContent) noteContent = await this.getFullHTML();
            if (!noteContent) return;

            noteContent
                .querySelectorAll(".minimap-frame, .minimap-slider")
                .forEach((el) => el.remove());
            this.syncTaskKanbanCollapse(noteContent);

            const stylesHTML = this.plugin.getStylesHTML();
            const themeClass = document.body.classList.contains("theme-dark")
                ? "theme-dark"
                : "theme-light";
            const cssVars = this.plugin.getCssVars();
            const sizerHeight =
                this.scroller?.firstChild?.getBoundingClientRect().height || 0;
            const scrollHeight = this.scroller?.scrollHeight || 0;
            const bottomOverscrollHeight = Math.max(
                0,
                this.bottomOverscrollHeight || scrollHeight - sizerHeight
            );
            this.bottomOverscrollHeight = bottomOverscrollHeight;

            const html = `
		<!DOCTYPE html>
		<html>
		<head>${stylesHTML}<style>${cssVars}
        .cursor-minimap-bottom-overscroll {
            height: ${bottomOverscrollHeight}px;
            background: #161616;
            flex: 0 0 auto;
        }
        .markdown-reading-view,
        .markdown-preview-view,
        .markdown-preview-sizer,
        .markdown-preview-section {
            height: auto !important;
            min-height: 0 !important;
            max-height: none !important;
            overflow: visible !important;
        }
        </style></head>
		<body style="background-color:${this.backgroundColor}" class="${themeClass} show-inline-title">${noteContent.innerHTML}<div class="cursor-minimap-bottom-overscroll"></div></body>
		</html>
	`;

            if (this.iframe && html !== this.lastIframeHTML) {
                this.lastIframeHTML = html;
                this.hasMeasuredIframeHeight = false;
                this.iframe.srcdoc = html;
            }
        } finally {
            this.isUpdatingIframe = false;
            if (this.needsIframeUpdate) {
                this.needsIframeUpdate = false;
                window.setTimeout(() => this.updateIframe(), 0);
            }
        }
    },

    onIframeLoad() {
        const body = this.iframe?.contentDocument?.body;
        if (!body || !this.visibleHeight) return;
        const sizer = body.querySelector(".markdown-preview-sizer");
        const contentElement = sizer || body;
        const contentRect = contentElement.getBoundingClientRect();
        const overscroll = body.querySelector(".cursor-minimap-bottom-overscroll");
        const overscrollHeight = overscroll?.getBoundingClientRect().height || 0;
        const iframeContentHeight =
            Math.max(contentElement.scrollHeight || 0, contentRect.height || 0) +
            overscrollHeight;

        if (Math.abs(iframeContentHeight - (this.fullHeight || 0)) > 2) {
            this.documentHeight = iframeContentHeight;
            this.hasMeasuredIframeHeight = true;
            this.resize(iframeContentHeight, this.visibleHeight);
        } else {
            this.hasMeasuredIframeHeight = true;
        }
    },

    syncTaskKanbanCollapse(noteContent) {
        const collapsed = this.isTaskKanbanCollapsedInSource();
        const kanbanCallouts = Array.from(
            noteContent.querySelectorAll(".callout")
        ).filter((callout) => {
            const dataCallout = callout.getAttribute("data-callout") || "";
            return (
                dataCallout === "todo" ||
                dataCallout === "task-kanban" ||
                !!callout.querySelector(
                    ".task-kanban-inline-marker, .task-kanban-inline-card"
                ) ||
                /Task Kanban/i.test(callout.textContent || "")
            );
        });

        for (const callout of kanbanCallouts) {
            callout.classList.toggle("is-collapsed", collapsed);
            callout.setAttribute("data-callout-fold", collapsed ? "-" : "+");
            const content = callout.querySelector(".callout-content");
            if (content) {
                content.style.display = collapsed ? "none" : "";
                content.toggleAttribute("hidden", collapsed);
            }
        }
    },

    isTaskKanbanCollapsedInSource() {
        return !!this.element.querySelector(
            ".callout.is-collapsed:has(.task-kanban-inline-marker), .callout[data-callout-fold='-']:has(.task-kanban-inline-marker), .callout.is-collapsed[data-callout='todo'], .callout[data-callout-fold='-'][data-callout='todo'], .callout.is-collapsed[data-callout='task-kanban'], .callout[data-callout-fold='-'][data-callout='task-kanban']"
        );
    },

    async getFullHTML() {
        if (!this.isReadModeActive()) return null;
        return await renderReadMode(this.plugin, this.element);
    },
};

},
"js/minimap-scroll": function(require, module, exports) {
module.exports = {
    getMinimapDragZoneRect() {
        const rect = this.iframe?.getBoundingClientRect();
        if (rect?.width && rect?.height) return rect;
        return this.container?.getBoundingClientRect();
    },

    isPointerInsideMinimapDragZone(event) {
        const rect = this.getMinimapDragZoneRect();
        if (!rect) return false;

        return (
            event.clientX >= rect.left &&
            event.clientX <= rect.right &&
            event.clientY >= rect.top &&
            event.clientY <= rect.bottom
        );
    },

    isPointerInsideMinimapDragColumn(event) {
        const rect = this.getMinimapDragZoneRect();
        if (!rect) return false;

        return event.clientX >= rect.left && event.clientX <= rect.right;
    },

    getSliderVisualHeight() {
        const yScale = this.yScale || this.scale || 1;
        const exactHeight = this.scroller.clientHeight * yScale;
        const zoneWidth = this.getMinimapDragZoneRect()?.width || 0;
        const minHeight = this.yScale < this.scale ? zoneWidth / 2 : 1;
        return Math.max(minHeight, exactHeight, 1);
    },

    getSliderTravelMetrics() {
        const zoneRect = this.getMinimapDragZoneRect();
        const containerRect = this.container.getBoundingClientRect();
        const sliderHeight = this.getSliderVisualHeight();
        const maxScroll = Math.max(
            0,
            this.scroller.scrollHeight - this.scroller.clientHeight
        );
        const topBase = zoneRect.top - containerRect.top;
        const travelHeight = Math.max(0, zoneRect.height - sliderHeight / 2);

        return {
            maxScroll,
            sliderHeight,
            topBase,
            travelHeight,
        };
    },

    updateSliderScroll() {
        if (!this.scroller) return;
        const scrollTop = this.scroller.scrollTop;
        if (scrollTop !== this._lastScrollTop) {
            this.minimapScrollOffset = 0;
            this._lastScrollTop = scrollTop;
        }

        const { maxScroll, sliderHeight, topBase, travelHeight } =
            this.getSliderTravelMetrics();
        const scrollRatio = maxScroll ? scrollTop / maxScroll : 0;
        const boxTop = topBase + scrollRatio * travelHeight;
        this.iframe.style.top = `${this.topOffset || 0}px`;
        this.slider.style.height = `${sliderHeight}px`;
        this.slider.style.top = `${boxTop}px`;
    },

    onSliderMouseDown(event) {
        event.preventDefault();
        this.isDragging = true;
        this.slider.classList.add("dragging");

        const sliderRect = this.slider.getBoundingClientRect();
        this.dragOffsetY = event.clientY - sliderRect.top;

        document.addEventListener("mousemove", this.onSliderMouseMove);
        document.addEventListener("mouseup", this.onSliderMouseUp);
    },

    minimapScrollToY(clientY) {
        const rect = this.getMinimapDragZoneRect();
        const { maxScroll, sliderHeight, travelHeight } =
            this.getSliderTravelMetrics();
        const y = clientY - rect.top - sliderHeight / 2;
        const scrollRatio = travelHeight ? y / travelHeight : 0;
        this.scroller.scrollTop = Math.max(
            0,
            Math.min(maxScroll, scrollRatio * maxScroll)
        );
        this.minimapScrollOffset = 0;
        this.updateSliderScroll();
    },

    onMinimapMouseDown(event) {
        if (event.button !== 0 || !this.scroller) return;
        if (
            event.target instanceof Element &&
            event.target.closest(".minimap-slider")
        ) {
            return;
        }
        if (!this.isPointerInsideMinimapDragZone(event)) return;
        event.preventDefault();
        event.stopPropagation();
        this.minimapScrollToY(event.clientY);
        this.isMinimapDragging = true;
        document.addEventListener("mousemove", this.onMinimapDragMove);
        document.addEventListener("mouseup", this.onMinimapDragUp);
    },

    onMinimapDragMove(event) {
        if (!this.isMinimapDragging) return;
        if (!this.isPointerInsideMinimapDragZone(event)) {
            this.onMinimapDragUp();
            return;
        }
        this.minimapScrollToY(event.clientY);
    },

    onMinimapDragUp() {
        this.isMinimapDragging = false;
        document.removeEventListener("mousemove", this.onMinimapDragMove);
        document.removeEventListener("mouseup", this.onMinimapDragUp);
    },

    onMinimapWheel(event) {
        if (!this.scroller) return;
        event.preventDefault();
        event.stopPropagation();
        const delta =
            event.deltaMode === 1
                ? event.deltaY * 40
                : event.deltaMode === 2
                  ? event.deltaY * this.scroller.clientHeight
                  : event.deltaY;
        this.scroller.scrollTop += delta;
        this.minimapScrollOffset = 0;
        this.updateSliderScroll();
    },

    onSliderMouseMove(event) {
        if (!this.isDragging) return;
        if (!this.isPointerInsideMinimapDragColumn(event)) {
            this.onSliderMouseUp();
            return;
        }

        const zoneRect = this.getMinimapDragZoneRect();
        let offsetY =
            event.clientY -
            zoneRect.top -
            this.dragOffsetY;

        const { maxScroll, travelHeight } = this.getSliderTravelMetrics();

        offsetY = Math.max(0, Math.min(offsetY, travelHeight));
        this.scroller.scrollTop = travelHeight
            ? (offsetY / travelHeight) * maxScroll
            : 0;

        this.updateSliderScroll();
    },

    onSliderMouseUp() {
        this.isDragging = false;
        this.slider.classList.remove("dragging");
        document.removeEventListener("mousemove", this.onSliderMouseMove);
        document.removeEventListener("mouseup", this.onSliderMouseUp);
    },
};

},
"js/renderers": function(require, module, exports) {
const { MarkdownRenderer, MarkdownView } = require("obsidian");
const { sleep } = require("./utils");

function getMarkdownViewForElement(plugin, sourceElement) {
    const activeView = plugin.app.workspace.getActiveViewOfType(MarkdownView);
    return (
        plugin.app.workspace
            .getLeavesOfType("markdown")
            .map((leaf) => leaf.view)
            .find((view) => view.contentEl === sourceElement) || activeView
    );
}

async function renderMarkdownDocument(plugin, sourceElement) {
    const matchingView = getMarkdownViewForElement(plugin, sourceElement);
    const file = matchingView?.file || plugin.app.workspace.getActiveFile();
    if (!file) return null;

    const noteContent = document.createElement("div");
    noteContent.className = "markdown-reading-view";
    const preview = document.createElement("div");
    preview.className = "markdown-preview-view markdown-rendered";
    const destination = document.createElement("div");
    destination.className = "markdown-preview-sizer markdown-preview-section";
    preview.appendChild(destination);
    noteContent.appendChild(preview);

    const markdown =
        typeof matchingView?.getViewData === "function"
            ? await matchingView.getViewData()
            : await plugin.app.vault.read(file);
    await MarkdownRenderer.render(
        plugin.app,
        markdown,
        destination,
        file.path,
        plugin
    );
    return noteContent;
}

async function renderReadMode(plugin, sourceElement) {
    return await renderMarkdownDocument(plugin, sourceElement);
}

async function renderEditMode(plugin, sourceElement, helperElement, scroller) {
    const renderedDocument = await renderMarkdownDocument(plugin, sourceElement);
    if (renderedDocument) return renderedDocument;

    let noteContent;
    if (helperElement) {
        noteContent = helperElement.cloneNode(true);
    } else {
        const sizer = scroller.firstChild;
        const element = scroller.parentElement.parentElement.parentElement;
        sizer.style = "transform-origin: top right; scale: .1;";
        element.offsetWidth;
        await sleep(10);

        noteContent = element.cloneNode(true);
        sizer.style = "";
    }

    noteContent.querySelectorAll(".cm-sizer").forEach((el) => {
        el.style = "";
    });
    noteContent
        .querySelectorAll(".markdown-source-view > :not(.cm-editor)")
        .forEach((el) => el.remove());

    return noteContent;
}

module.exports = {
    renderEditMode,
    renderReadMode,
};

},
"js/utils": function(require, module, exports) {
function throttle(fn, limit, options = { leading: false, trailing: true }) {
    let inThrottle = false;
    let lastArgs;
    let lastThis;

    const invoke = () => {
        if (lastArgs) {
            fn.apply(lastThis, lastArgs);
            lastArgs = lastThis = null;
            setTimeout(invoke, limit);
        } else {
            inThrottle = false;
        }
    };

    return function (...args) {
        if (!inThrottle) {
            if (options.leading) {
                fn.apply(this, args);
            } else {
                lastArgs = args;
                lastThis = this;
            }
            inThrottle = true;
            setTimeout(invoke, limit);
        } else if (options.trailing) {
            lastArgs = args;
            lastThis = this;
        }
    };
}

function toRGBAAlpha(color, alpha) {
    if (color.startsWith("#")) {
        let hex = color.replace("#", "");
        if (hex.length === 3) {
            hex = hex
                .split("")
                .map((x) => x + x)
                .join("");
        }
        const num = parseInt(hex, 16);
        const r = (num >> 16) & 255;
        const g = (num >> 8) & 255;
        const b = num & 255;
        return `rgba(${r},${g},${b},${alpha})`;
    }

    if (color.startsWith("rgb")) {
        const nums = color.match(/[\d.]+/g);
        if (nums.length >= 3) {
            return `rgba(${nums[0]},${nums[1]},${nums[2]},${alpha})`;
        }
    }

    return color;
}

function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

module.exports = {
    sleep,
    throttle,
    toRGBAAlpha,
};

}
};
const __cache = Object.create(null);
function __normalize(id) {
    const parts = [];
    for (const part of id.split("/")) {
        if (!part || part === ".") continue;
        if (part === "..") parts.pop();
        else parts.push(part);
    }
    return parts.join("/").replace(/\.js$/, "");
}
function __dirnameOf(id) {
    const slash = id.lastIndexOf("/");
    return slash === -1 ? "" : id.slice(0, slash);
}
function __resolve(request, parentId) {
    if (!request.startsWith(".")) return request;
    return __normalize(__dirnameOf(parentId) + "/" + request);
}
function __require(request, parentId) {
    const id = __resolve(request, parentId || "main");
    if (!__modules[id]) return __nativeRequire(request);
    if (__cache[id]) return __cache[id].exports;
    const module = { exports: {} };
    __cache[id] = module;
    const localRequire = (nextRequest) => __require(nextRequest, id);
    __modules[id](localRequire, module, module.exports);
    return module.exports;
}
module.exports = __require("./main", "main");
