// Generated by build.js from files in js/. Edit js/*, then run: node build.js
const __nativeRequire = require;
const __modules = {
"main": function(require, module, exports) {
const { Plugin } = require("obsidian");

const lifecycleMethods = require("./js/plugin-lifecycle");
const settingsMethods = require("./js/plugin-settings");
const minimapManagerMethods = require("./js/plugin-minimap-manager");
const helperLeafMethods = require("./js/plugin-helper-leaves");
const diskCacheMethods = require("./js/plugin-disk-cache");

class NoteMinimap extends Plugin {
    activeNoteView = null;
    updateNeeded = false;
    minimapInstances = new Map();
    stylesHTMLCache = null;
    cssVarsCache = null;
    helperLeafIds = new Map();
}

Object.assign(
    NoteMinimap.prototype,
    lifecycleMethods,
    settingsMethods,
    minimapManagerMethods,
    helperLeafMethods,
    diskCacheMethods
);

module.exports = NoteMinimap;

},
"js/plugin-lifecycle": function(require, module, exports) {
const { MarkdownView, debounce } = require("obsidian");
const MinimapSettingTab = require("./settings-tab");
const { throttle } = require("./utils");

module.exports = {
    async onload() {
        console.log("NoteMinimap Loaded");
        this.snapshotCache = { filePath: null, mtime: null, html: null };

        const resized = new Set();
        const resize = throttle(() => {
            for (const el of resized) {
                for (const [element, note] of this.minimapInstances.entries()) {
                    if (element === el) {
                        note.onResize();
                        break;
                    }
                }
            }
            resized.clear();
        }, 1000);

        this.resizeObserver = new ResizeObserver((entries) => {
            for (const entry of entries) resized.add(entry.target);
            resize();
        });

        this.modeObserver = new MutationObserver((entries) => {
            const entry = entries[0];
            const noteInstance = this.minimapInstances.get(
                entry.target.parentElement
            );
            if (entry.attributeName === "style") noteInstance?.modeChange();
            this.updateElementMinimap();
        });

        this.registerEvent(
            this.app.workspace.on("active-leaf-change", (newActiveLeaf) => {
                if (!newActiveLeaf?.view) return;
                this.checkAndDealWithUserOpeningHelperLeaves(newActiveLeaf);
                this.updateElementMinimap();
                this.activeNoteView = newActiveLeaf.view;
                this.updateElementMinimap();

                if (newActiveLeaf?.view?.getViewType() === "markdown") {
                    if (this.settings.betterRendering) {
                        clearTimeout(this._helperLeafTimer);
                        this._helperLeafTimer = window.setTimeout(
                            () => this.openHelperForLeaf(newActiveLeaf),
                            600
                        );
                    }
                    this.addToggleButtonToLeaf(newActiveLeaf);
                }
            })
        );

        this.debouncedUpdateMinimap = debounce(
            () => this.updateElementMinimap(),
            700,
            false
        );
        this.registerEvent(
            this.app.workspace.on("editor-change", this.debouncedUpdateMinimap)
        );
        this.registerEvent(
            this.app.vault.on("modify", async (file) => {
                const leaf = this.app.workspace.getLeavesOfType("markdown")
                    .find(l => l.view.file?.path === file.path);
                if (!leaf) return;
                const minimap = this.minimapInstances.get(leaf.view.contentEl);
                if (minimap) await minimap.prerenderForCache();
            })
        );
        this.registerDomEvent(document, "click", (event) => {
            const target = event.target;
            if (!(target instanceof Element)) return;
            if (
                target.closest(
                    ".callout-title, .collapse-indicator, .task-kanban-inline-action, .heading-collapse-indicator"
                )
            ) {
                window.setTimeout(() => {
                    this.snapshotCache = { filePath: null, mtime: null, html: null };
                    const activeEl = this.activeNoteView?.contentEl;
                    if (activeEl) {
                        const minimap = this.minimapInstances.get(activeEl);
                        if (minimap) {
                            minimap.lastIframeHTML = "";
                            minimap.onResize();
                        }
                    }
                    this.updateElementMinimap();
                }, 250);
            }
        }, true);

        const updateHelpers = throttle(() => {
            this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
                this.updateHelperForLeaf(leaf);
            });
            this.updateElementMinimap();
        }, 500);

        this.registerLayoutChangeHandler(updateHelpers);

        await this.loadSettings();
        await this.initDiskCache();
        this.addSettingTab(new MinimapSettingTab(this));
        this.app.workspace.onLayoutReady(() => {
            this.activeNoteView =
                this.app.workspace.getActiveViewOfType(MarkdownView);
            this.injectMinimapIntoAllNotes();
        });
    },

    registerLayoutChangeHandler(updateHelpers) {
        this.registerEvent(
            this.app.workspace.on("layout-change", () => {
                if (this.settings.betterRendering) {
                    this.detachRedundantHelperLeavesAndRestoreMissing();
                    updateHelpers();
                }

                this.minimapInstances
                    .get(this.activeNoteView?.contentEl)
                    ?.onResize();

                const openEls = new Set(
                    this.app.workspace
                        .getLeavesOfType("markdown")
                        .map((leaf) => leaf.view.contentEl)
                );
                for (const [el, note] of this.minimapInstances.entries()) {
                    if (!openEls.has(el)) {
                        note.destroy();
                        this.minimapInstances.delete(el);
                        this.resizeObserver.unobserve(el);
                    }
                }
            })
        );
    },

    onunload() {
        if (this.debouncedUpdateMinimap?.cancel) {
            this.debouncedUpdateMinimap.cancel();
        }

        this.minimapInstances.forEach((noteInstance) => noteInstance.destroy());
        this.resizeObserver.disconnect();
        this.modeObserver.disconnect();

        document
            .querySelectorAll(".minimap-toggle-button")
            .forEach((button) => button.remove());
        this.detachAllHelperLeaves();

        console.log("NoteMinimap Unloaded");
    },
};

},
"js/plugin-settings": function(require, module, exports) {
module.exports = {
    async loadSettings() {
        this.settings = Object.assign(
            {
                enabledByDefault: true,
                betterRendering: true,
                scale: 0.12,
                minimapOpacity: 0.3,
                sliderOpacity: 0.3,
                topOffset: 0,
            },
            await this.loadData()
        );

        if (!Number.isFinite(this.settings.scale)) {
            this.settings.scale = 0.12;
        }
    },

    async saveSettings() {
        await this.saveData(this.settings);

        for (const note of this.minimapInstances.values()) {
            note.updateSettings(this.settings);
        }
    },

    getStylesHTML() {
        if (this.stylesHTMLCache) return this.stylesHTMLCache;

        const styleElements = Array.from(
            document.head.querySelectorAll('style, link[rel="stylesheet"]')
        );
        this.stylesHTMLCache = styleElements.map((el) => el.outerHTML).join("\n");
        return this.stylesHTMLCache;
    },

    getCssVars() {
        if (this.cssVarsCache) return this.cssVarsCache;

        const rootStyles = getComputedStyle(document.body);
        let cssVars = ":root {\n";
        for (let i = 0; i < rootStyles.length; i++) {
            const prop = rootStyles[i];
            if (prop.startsWith("--")) {
                cssVars += `  ${prop}: ${rootStyles.getPropertyValue(prop)};\n`;
            }
        }
        cssVars += "}\n::-webkit-scrollbar { display: none; }";
        this.cssVarsCache = cssVars;
        return cssVars;
    },
};

},
"js/plugin-minimap-manager": function(require, module, exports) {
const { setIcon } = require("obsidian");
const Minimap = require("./minimap");
const { sleep } = require("./utils");

module.exports = {
    injectMinimapIntoAllNotes() {
        const leaves = this.app.workspace.getLeavesOfType("markdown");
        for (const leaf of leaves) {
            if (this.settings.betterRendering) this.openHelperForLeaf(leaf);
            this.addToggleButtonToLeaf(leaf);
            this.updateElementMinimap(
                leaf.view.contentEl,
                this.helperLeafIds.get(leaf.id)
            );
        }
    },

    async updateElementMinimap(element, helperLeafId) {
        await sleep(100);
        const activeLeaf = this.app.workspace.activeLeaf;
        helperLeafId = activeLeaf
            ? this.helperLeafIds.get(activeLeaf.id)
            : helperLeafId;

        if (!element) {
            if (!this.activeNoteView) return;
            element = this.activeNoteView.contentEl;
        }

        if (
            !element.querySelector(".markdown-source-view") ||
            !element.querySelector(".markdown-preview-view")
        ) {
            return;
        }

        const existing = this.minimapInstances.get(element);
        const isReadMode =
            element.querySelector(".markdown-source-view")?.clientHeight === 0;

        if (!isReadMode) {
            if (existing) {
                existing.container.style.display = "none";
            }
            return;
        }

        if (element.classList.contains("minimap-disabled")) {
            if (existing) {
                existing.container.style.display = "none";
            }
            return;
        }

        if (this.minimapInstances.has(element)) {
            const noteInstance = this.minimapInstances.get(element);
            noteInstance.container.style.display = "";
            noteInstance.updateIframe();
        } else {
            const minimapInstance = new Minimap(
                this,
                element,
                this.settings,
                helperLeafId
            );
            this.minimapInstances.set(element, minimapInstance);
            this.resizeObserver.observe(element);
            this.modeObserver.observe(minimapInstance.sourceView, {
                attributes: true,
            });
        }
    },

    addToggleButtonToLeaf(leaf) {
        const viewActions = leaf.view.containerEl.querySelector(".view-actions");
        if (!viewActions) return;
        if (viewActions.querySelector(".minimap-toggle-button")) return;

        const button = document.createElement("button");
        button.className = "clickable-icon view-actions minimap-toggle-button";
        button.setAttribute("aria-label", "Toggle Minimap");
        setIcon(button, "star-list");

        const contentEl = leaf.view.contentEl;
        button.onclick = () => {
            contentEl.classList.toggle("minimap-disabled");
            this.updateElementMinimap(contentEl);
        };

        if (!this.settings.enabledByDefault) {
            contentEl.classList.add("minimap-disabled");
        }

        viewActions.prepend(button);
    },
};

},
"js/plugin-helper-leaves": function(require, module, exports) {
module.exports = {
    async openHelperForLeaf(leaf) {
        if (!leaf) return;
        if (this.helperLeafIds.has(leaf.id)) return;
        if ([...this.helperLeafIds.values()].includes(leaf.id)) return;

        const file = leaf.view.file;
        if (!file) return;

        const rightLeaf = this.app.workspace.getRightLeaf(false);
        this.helperLeafIds.set(leaf.id, rightLeaf.id);

        if (rightLeaf.tabHeaderEl) {
            rightLeaf.tabHeaderEl.style.setProperty("display", "none", "important");
        }

        this.updateHelperForLeaf(leaf);
    },

    detachRedundantHelperLeavesAndRestoreMissing() {
        if (this._updatingHelperLeaves) return;
        this._updatingHelperLeaves = true;
        try {
            this.helperLeafIds.forEach((helperLeafId, originalLeafId) => {
                if (this.app.workspace.getLeafById(originalLeafId)) {
                    if (!this.app.workspace.getLeafById(helperLeafId)) {
                        this.helperLeafIds.delete(originalLeafId);
                        const originalLeaf =
                            this.app.workspace.getLeafById(originalLeafId);
                        this.openHelperForLeaf(originalLeaf);
                    }
                } else {
                    const helperLeaf = this.app.workspace.getLeafById(helperLeafId);
                    if (helperLeaf) helperLeaf.detach();
                    this.helperLeafIds.delete(originalLeafId);
                }
            });
        } finally {
            this._updatingHelperLeaves = false;
        }
    },

    checkAndDealWithUserOpeningHelperLeaves(newActiveLeaf) {
        if (
            newActiveLeaf?.id &&
            [...this.helperLeafIds.values()].includes(newActiveLeaf.id)
        ) {
            newActiveLeaf.detach();
        }
    },

    detachAllHelperLeaves() {
        this.helperLeafIds.forEach((helperLeafId) => {
            this.app.workspace.getLeafById(helperLeafId)?.detach();
        });
    },

    async updateHelperForLeaf(leaf) {
        const helperLeaf = this.app.workspace.getLeafById(
            this.helperLeafIds.get(leaf?.id)
        );
        if (!helperLeaf) return;

        const newState = leaf.view.getState();
        await helperLeaf.setViewState({
            type: "markdown",
            state: newState,
        });
    },
};

},
"js/plugin-disk-cache": function(require, module, exports) {
const CACHE_SUBDIR = "temp";

module.exports = {
    async initDiskCache() {
        this._cacheDir = `${this.manifest.dir}/${CACHE_SUBDIR}`;
        if (!await this.app.vault.adapter.exists(this._cacheDir)) {
            await this.app.vault.adapter.mkdir(this._cacheDir);
        }
        this.cleanupDiskCache().catch(() => {});
    },

    _getCacheKey(filePath) {
        return encodeURIComponent(filePath);
    },

    async loadFromDiskCache(filePath, mtime) {
        if (!this._cacheDir || !filePath || !mtime) return null;
        try {
            const key = this._getCacheKey(filePath);
            const metaPath = `${this._cacheDir}/${key}.json`;
            if (!await this.app.vault.adapter.exists(metaPath)) return null;
            const meta = JSON.parse(await this.app.vault.adapter.read(metaPath));
            if (meta.mtime !== mtime) return null;
            const htmlPath = `${this._cacheDir}/${key}.html`;
            if (!await this.app.vault.adapter.exists(htmlPath)) return null;
            return await this.app.vault.adapter.read(htmlPath);
        } catch {
            return null;
        }
    },

    saveToDiskCache(filePath, mtime, html) {
        if (!this._cacheDir || !filePath || !mtime || !html) return;
        const key = this._getCacheKey(filePath);
        this.app.vault.adapter
            .write(`${this._cacheDir}/${key}.json`, JSON.stringify({ filePath, mtime }))
            .catch(() => {});
        this.app.vault.adapter
            .write(`${this._cacheDir}/${key}.html`, html)
            .catch(() => {});
    },

    async cleanupDiskCache() {
        if (!this._cacheDir) return;
        try {
            if (!await this.app.vault.adapter.exists(this._cacheDir)) return;
            const listing = await this.app.vault.adapter.list(this._cacheDir);
            for (const filePath of listing.files) {
                if (!filePath.endsWith(".json")) continue;
                try {
                    const meta = JSON.parse(await this.app.vault.adapter.read(filePath));
                    if (!this.app.vault.getAbstractFileByPath(meta.filePath)) {
                        await this.app.vault.adapter.remove(filePath);
                        const htmlPath = filePath.replace(/\.json$/, ".html");
                        if (await this.app.vault.adapter.exists(htmlPath)) {
                            await this.app.vault.adapter.remove(htmlPath);
                        }
                    }
                } catch { /* skip corrupted entries */ }
            }
        } catch { /* ignore cleanup errors */ }
    },
};

},
"js/settings-tab": function(require, module, exports) {
const { Notice, PluginSettingTab, Setting } = require("obsidian");

class MinimapSettingTab extends PluginSettingTab {
    constructor(plugin) {
        super(plugin.app, plugin);
        this.plugin = plugin;
    }

    display() {
        const { containerEl } = this;
        containerEl.empty();

        new Setting(containerEl)
            .setName("Enable by default")
            .setDesc("Already opened notes will not be affected by changing this")
            .addToggle((toggle) => {
                toggle
                    .setValue(this.plugin.settings.enabledByDefault)
                    .onChange((value) => {
                        this.plugin.settings.enabledByDefault = value;
                        this.plugin.saveSettings();
                    });
            });

        new Setting(containerEl)
            .setName("Better Rendering (in development)")
            .setDesc(
                "Use a hidden helper note to render the minimap, improving flickering. Changing this restarts the plugin"
            )
            .addToggle((toggle) => {
                toggle
                    .setValue(this.plugin.settings.betterRendering)
                    .onChange(async (value) => {
                        this.plugin.settings.betterRendering = value;
                        await this.plugin.saveSettings();
                        await this.app.plugins.disablePlugin("cursor-minimap");
                        await this.app.plugins.enablePlugin("cursor-minimap");
                        this.app.setting.openTabById("cursor-minimap");
                        new Notice("Note Minimap: Restarted plugin for Better Rendering change.", 3000);
                    });
            });

        this.addSliderWithInput(
            "Scale",
            "Content zoom level — controls column width and text size in the minimap",
            "scale", 0.05, 0.3, 0.01,
            (v) => `${Math.round(v * 100)}%`,
            (s) => { const n = parseFloat(s); return n > 1 ? n / 100 : n; }
        );
        this.addSliderWithInput(
            "Opacity",
            "Background opacity of the minimap",
            "minimapOpacity", 0.05, 1, 0.01,
            (v) => `${Math.round(v * 100)}%`,
            (s) => { const n = parseFloat(s); return n > 1 ? n / 100 : n; }
        );
        this.addSliderWithInput(
            "Slider Opacity",
            "Opacity of the viewport indicator rectangle",
            "sliderOpacity", 0.05, 1, 0.01,
            (v) => `${Math.round(v * 100)}%`,
            (s) => { const n = parseFloat(s); return n > 1 ? n / 100 : n; }
        );
        this.addSliderWithInput(
            "Top Offset",
            "Push minimap down from the top edge (px) — for plugin toolbars",
            "topOffset", 0, 100, 1,
            (v) => `${v}px`,
            (s) => parseInt(s)
        );

    }

    addSliderWithInput(name, description, key, min, max, step, format, parse) {
        let sliderComp, textComp;
        new Setting(this.containerEl)
            .setName(name)
            .setDesc(description)
            .addSlider((slider) => {
                sliderComp = slider;
                slider
                    .setLimits(min, max, step)
                    .setValue(this.plugin.settings[key])
                    .setDynamicTooltip()
                    .onChange((value) => {
                        this.plugin.settings[key] = value;
                        textComp?.setValue(format(value));
                        this.plugin.saveSettings();
                    });
            })
            .addText((text) => {
                textComp = text;
                text.setValue(format(this.plugin.settings[key]));
                text.inputEl.style.width = "58px";
                text.inputEl.style.textAlign = "right";

                const applyText = () => {
                    const parsed = parse(text.getValue());
                    if (!isFinite(parsed)) return;
                    const val = +Math.max(min, Math.min(max, parsed)).toFixed(4);
                    this.plugin.settings[key] = val;
                    sliderComp?.setValue(val);
                    text.setValue(format(val));
                    this.plugin.saveSettings();
                };
                text.inputEl.addEventListener("blur", applyText);
                text.inputEl.addEventListener("keydown", (e) => {
                    if (e.key === "Enter") applyText();
                });
            });
    }
}

module.exports = MinimapSettingTab;

},
"js/minimap": function(require, module, exports) {
const minimapSettingsMethods = require("./minimap-settings");
const minimapLayoutMethods = require("./minimap-layout");
const minimapRenderingMethods = require("./minimap-rendering");
const minimapScrollMethods = require("./minimap-scroll");

class Minimap {
    minimapScrollOffset = 0;
    minimapScrollTop = 0;
    _manualMinimapScroll = false;

    constructor(plugin, element, settings, helperLeafId) {
        this.plugin = plugin;
        this.element = element;
        this.helperLeafId = helperLeafId;
        this.helperElement =
            plugin.app.workspace.getLeafById(helperLeafId)?.view?.contentEl;
        this.lastIframeHTML = "";
        this.sourceView = element.querySelector(".markdown-source-view");

        this.updateSliderScroll = this.updateSliderScroll.bind(this);
        this.onSliderMouseDown = this.onSliderMouseDown.bind(this);
        this.onSliderMouseMove = this.onSliderMouseMove.bind(this);
        this.onSliderMouseUp = this.onSliderMouseUp.bind(this);
        this.onMinimapMouseDown = this.onMinimapMouseDown.bind(this);
        this.onMinimapDragMove = this.onMinimapDragMove.bind(this);
        this.onMinimapDragUp = this.onMinimapDragUp.bind(this);
        this.onMinimapWheel = this.onMinimapWheel.bind(this);
        this.onIframeLoad = this.onIframeLoad.bind(this);

        this.modeChange();
        this.setupElements();
        this.updateSettings(settings);

        this.scroller.addEventListener("scroll", this.updateSliderScroll);
        this.slider.addEventListener("mousedown", this.onSliderMouseDown);
        this.container.addEventListener("mousedown", this.onMinimapMouseDown);
        this.container.addEventListener("wheel", this.onMinimapWheel, {
            passive: false,
        });
    }

    destroy() {
        this.scroller.removeEventListener("scroll", this.updateSliderScroll);
        this.slider.removeEventListener("mousedown", this.onSliderMouseDown);
        this.iframe?.removeEventListener("load", this.onIframeLoad);
        this.container.removeEventListener("mousedown", this.onMinimapMouseDown);
        this.container.removeEventListener("wheel", this.onMinimapWheel);
        this.edgeToggle?.remove();
        document.removeEventListener("mousemove", this.onSliderMouseMove);
        document.removeEventListener("mouseup", this.onSliderMouseUp);
        document.removeEventListener("mousemove", this.onMinimapDragMove);
        document.removeEventListener("mouseup", this.onMinimapDragUp);

        this.container.remove();
        this.iframe = null;
        this.slider = null;
        this.container = null;
        this.element.style.removeProperty("--cursor-minimap-reserved");
    }
}

Object.assign(
    Minimap.prototype,
    minimapSettingsMethods,
    minimapLayoutMethods,
    minimapRenderingMethods,
    minimapScrollMethods
);

module.exports = Minimap;

},
"js/minimap-settings": function(require, module, exports) {
const { toRGBAAlpha } = require("./utils");

module.exports = {
    _getEffectiveScale() {
        return this.scale;
    },

    updateSettings(settings) {
        this.scale = settings.scale;
        this.minimapOpacity = settings.minimapOpacity;
        this.sliderOpacity = settings.sliderOpacity;
        this.topOffset = settings.topOffset;

        this.backgroundColor = toRGBAAlpha(
            document
                .querySelector(".view-content")
                .getCssPropertyValue("background-color"),
            this.minimapOpacity
        );

        if (this.iframe && this.slider) {
            this.updateSettingsInCSS();
            this.onResize();
            this.updateIframe();
            this.updateSliderScroll();
        }
    },

    updateSettingsInCSS() {
        const effectiveScale = this._getEffectiveScale();
        if (this.container) {
            this.container.style.setProperty("--scale", effectiveScale);
            this.container.style.setProperty("--y-scale", this.yScale || effectiveScale);
        }
        if (this.slider) this.slider.style.opacity = this.sliderOpacity;
        if (this.iframe) this.iframe.style.top = `${this.topOffset}px`;
        this.updateReservedWidth();
    },
};

},
"js/minimap-layout": function(require, module, exports) {
const { sleep } = require("./utils");
const { setIcon } = require("obsidian");

module.exports = {
    isReadModeActive() {
        return this.sourceView.clientHeight === 0;
    },

    modeChange() {
        if (!this.isReadModeActive()) {
            this.plugin.updateElementMinimap(this.element);
            return;
        }

        this.changeScroller(
            this.element.querySelector(
                ".markdown-preview-view"
            )
        );
        this.updateIframe();
    },

    changeScroller(newScroller) {
        if (this.scroller) {
            this.scroller.removeEventListener(
                "scroll",
                this.updateSliderScroll
            );
        }
        this.scroller = newScroller;
        if (this.scroller) {
            this.scroller.addEventListener("scroll", this.updateSliderScroll);
            this.onResize();
        }
    },

    async onResize() {
        await sleep(300);
        if (this.container?.style.display === "none") return;

        const visibleHeight = this.scroller.getBoundingClientRect().height;
        const sizerHeight =
            this.scroller.firstChild?.getBoundingClientRect().height || 0;
        const scrollHeight = this.scroller.scrollHeight || 0;
        this.bottomOverscrollHeight = Math.max(0, scrollHeight - sizerHeight);

        if (!this.hasMeasuredIframeHeight) {
            this.documentHeight = sizerHeight || scrollHeight;
        }
        const fullHeight = this.hasMeasuredIframeHeight
            ? this.documentHeight
            : this.documentHeight + this.bottomOverscrollHeight;
        this.resize(fullHeight, visibleHeight);
    },

    resize(fullHeight, visibleHeight) {
        this.fullHeight = Math.max(1, fullHeight || 1);
        this.visibleHeight = Math.max(1, visibleHeight || 1);
        this.yScale = this._getEffectiveScale();
        this.effectiveIframeHeight = Math.max(this.fullHeight, Math.ceil(this.visibleHeight / this.yScale));
        if (this.container) {
            this.container.style.setProperty("--scale", this.yScale);
            this.container.style.setProperty("--y-scale", this.yScale);
        }
        this.iframe.style.height = `${this.effectiveIframeHeight}px`;
        this.updateReservedWidth();
        this.updateSliderScroll();
    },

    setupElements() {
        this.element
            .querySelectorAll(
                ".minimap-container, .minimap-frame, .minimap-slider, .minimap-edge-toggle"
            )
            .forEach((element) => element.remove());

        this.container = document.createElement("div");
        this.container.className = "minimap-container";
        this.element.prepend(this.container);

        this.edgeToggle = document.createElement("button");
        this.edgeToggle.className = "minimap-edge-toggle";
        this.edgeToggle.type = "button";
        this.edgeToggle.setAttribute("aria-label", "Hide minimap");
        setIcon(this.edgeToggle, "chevron-right");
        this.edgeToggle.addEventListener("mousedown", (event) => {
            event.preventDefault();
            event.stopPropagation();
        });
        this.edgeToggle.addEventListener("click", (event) => {
            event.preventDefault();
            event.stopPropagation();
            this.toggleCollapsed();
        });
        this.container.appendChild(this.edgeToggle);

        this.iframe = document.createElement("iframe");
        this.iframe.className = "minimap-frame";
        this.iframe.addEventListener("load", this.onIframeLoad);
        this.container.appendChild(this.iframe);

        this.overlay = document.createElement("div");
        this.overlay.className = "minimap-click-overlay";
        this.container.appendChild(this.overlay);

        this.slider = document.createElement("div");
        this.slider.className = "minimap-slider";
        this.container.appendChild(this.slider);
        this.updateReservedWidth();
    },

    toggleCollapsed() {
        const collapsed = !this.container.classList.contains("minimap-collapsed");
        this.container.classList.toggle("minimap-collapsed", collapsed);
        this.edgeToggle.setAttribute(
            "aria-label",
            collapsed ? "Show minimap" : "Hide minimap"
        );
        setIcon(this.edgeToggle, collapsed ? "chevron-left" : "chevron-right");
        this.updateReservedWidth();
        if (!collapsed) this.onResize();
    },

    updateReservedWidth() {
        if (!this.element) return;
        if (this.container?.classList.contains("minimap-collapsed")) {
            this.element.style.setProperty("--cursor-minimap-reserved", "0px");
            return;
        }
        const width = Math.ceil(this.element.clientWidth * (this.scale || 0.12) + 12);
        this.element.style.setProperty("--cursor-minimap-reserved", `${width}px`);
    },
};

},
"js/minimap-rendering": function(require, module, exports) {
const { renderEditMode, renderReadMode } = require("./renderers");

module.exports = {
    getCurrentFile() {
        const leaves = this.plugin.app.workspace.getLeavesOfType("markdown");
        const view = leaves.map(l => l.view).find(v => v.contentEl === this.element);
        return view?.file || null;
    },

    async updateIframe(noteContent) {
        if (this.isUpdatingIframe) {
            this.needsIframeUpdate = true;
            return;
        }

        this.isUpdatingIframe = true;

        try {
            if (!noteContent) {
                const currentFile = this.getCurrentFile();
                const mtime = currentFile?.stat?.mtime;
                const cache = this.plugin.snapshotCache;

                // 1. memory cache hit
                if (cache.html && currentFile && cache.filePath === currentFile.path && cache.mtime === mtime) {
                    if (this.iframe && cache.html !== this.lastIframeHTML) {
                        this.lastIframeHTML = cache.html;
                        this.hasMeasuredIframeHeight = false;
                        this.iframe.srcdoc = cache.html;
                    }
                    return;
                }

                // 2. disk cache hit
                if (currentFile && mtime) {
                    const diskHtml = await this.plugin.loadFromDiskCache(currentFile.path, mtime);
                    if (diskHtml) {
                        this.plugin.snapshotCache = { filePath: currentFile.path, mtime, html: diskHtml };
                        if (this.iframe && diskHtml !== this.lastIframeHTML) {
                            this.lastIframeHTML = diskHtml;
                            this.hasMeasuredIframeHeight = false;
                            this.iframe.srcdoc = diskHtml;
                        }
                        return;
                    }
                }

                noteContent = await this.getFullHTML();
            }
            if (!noteContent) return;

            noteContent
                .querySelectorAll(".minimap-frame, .minimap-slider")
                .forEach((el) => el.remove());
            this.syncTaskKanbanCollapse(noteContent);

            const stylesHTML = this.plugin.getStylesHTML();
            const themeClass = document.body.classList.contains("theme-dark")
                ? "theme-dark"
                : "theme-light";
            const cssVars = this.plugin.getCssVars();
            const sizerHeight =
                this.scroller?.firstChild?.getBoundingClientRect().height || 0;
            const scrollHeight = this.scroller?.scrollHeight || 0;
            const bottomOverscrollHeight = Math.max(
                0,
                this.bottomOverscrollHeight || scrollHeight - sizerHeight
            );
            this.bottomOverscrollHeight = bottomOverscrollHeight;

            const html = `
		<!DOCTYPE html>
		<html>
		<head>${stylesHTML}<style>${cssVars}
        body { display: flex; flex-direction: column; min-height: 100%; }
        .cursor-minimap-bottom-overscroll {
            flex: 1 0 auto;
            min-height: ${bottomOverscrollHeight}px;
            background: #161616;
        }
        .markdown-reading-view,
        .markdown-preview-view,
        .markdown-preview-sizer,
        .markdown-preview-section {
            height: auto !important;
            min-height: 0 !important;
            max-height: none !important;
            overflow: visible !important;
        }
        </style></head>
		<body style="background-color:${this.backgroundColor}" class="${themeClass} show-inline-title">${noteContent.innerHTML}<div class="cursor-minimap-bottom-overscroll"></div></body>
		</html>
	`;

            if (this.iframe && html !== this.lastIframeHTML) {
                this.lastIframeHTML = html;
                this.hasMeasuredIframeHeight = false;
                this.iframe.srcdoc = html;
                const cacheFile = this.getCurrentFile();
                const cacheMtime = cacheFile?.stat?.mtime || null;
                this.plugin.snapshotCache = {
                    filePath: cacheFile?.path || null,
                    mtime: cacheMtime,
                    html,
                };
                this.plugin.saveToDiskCache(cacheFile?.path, cacheMtime, html);
            }
        } finally {
            this.isUpdatingIframe = false;
            if (this.needsIframeUpdate) {
                this.needsIframeUpdate = false;
                window.setTimeout(() => this.updateIframe(), 0);
            }
        }
    },

    async prerenderForCache() {
        if (this.isUpdatingIframe) return;
        const currentFile = this.getCurrentFile();
        if (!currentFile) return;

        const noteContent = await renderReadMode(this.plugin, this.element);
        if (!noteContent) return;

        noteContent
            .querySelectorAll(".minimap-frame, .minimap-slider")
            .forEach((el) => el.remove());
        this.syncTaskKanbanCollapse(noteContent);

        const stylesHTML = this.plugin.getStylesHTML();
        const themeClass = document.body.classList.contains("theme-dark")
            ? "theme-dark"
            : "theme-light";
        const cssVars = this.plugin.getCssVars();
        const sizerHeight =
            this.scroller?.firstChild?.getBoundingClientRect().height || 0;
        const scrollHeight = this.scroller?.scrollHeight || 0;
        const bottomOverscrollHeight = Math.max(
            0,
            this.bottomOverscrollHeight || scrollHeight - sizerHeight
        );

        const html = `
		<!DOCTYPE html>
		<html>
		<head>${stylesHTML}<style>${cssVars}
        body { display: flex; flex-direction: column; min-height: 100%; }
        .cursor-minimap-bottom-overscroll {
            flex: 1 0 auto;
            min-height: ${bottomOverscrollHeight}px;
            background: #161616;
        }
        .markdown-reading-view,
        .markdown-preview-view,
        .markdown-preview-sizer,
        .markdown-preview-section {
            height: auto !important;
            min-height: 0 !important;
            max-height: none !important;
            overflow: visible !important;
        }
        </style></head>
		<body style="background-color:${this.backgroundColor}" class="${themeClass} show-inline-title">${noteContent.innerHTML}<div class="cursor-minimap-bottom-overscroll"></div></body>
		</html>
	`;

        const cacheMtime = currentFile.stat?.mtime || null;
        this.plugin.snapshotCache = {
            filePath: currentFile.path,
            mtime: cacheMtime,
            html,
        };
        this.plugin.saveToDiskCache(currentFile.path, cacheMtime, html);
    },

    onIframeLoad() {
        const body = this.iframe?.contentDocument?.body;
        if (!body || !this.visibleHeight) return;
        const sizer = body.querySelector(".markdown-preview-sizer");
        const contentElement = sizer || body;
        const contentRect = contentElement.getBoundingClientRect();
        const overscroll = body.querySelector(".cursor-minimap-bottom-overscroll");
        const overscrollHeight = overscroll?.getBoundingClientRect().height || 0;
        const iframeContentHeight =
            Math.max(contentElement.scrollHeight || 0, contentRect.height || 0) +
            overscrollHeight;

        if (Math.abs(iframeContentHeight - (this.fullHeight || 0)) > 2) {
            this.documentHeight = iframeContentHeight;
            this.hasMeasuredIframeHeight = true;
            this.resize(iframeContentHeight, this.visibleHeight);
        } else {
            this.hasMeasuredIframeHeight = true;
        }
    },

    syncTaskKanbanCollapse(noteContent) {
        const collapsed = this.isTaskKanbanCollapsedInSource();
        const kanbanCallouts = Array.from(
            noteContent.querySelectorAll(".callout")
        ).filter((callout) => {
            const dataCallout = callout.getAttribute("data-callout") || "";
            return (
                dataCallout === "todo" ||
                dataCallout === "task-kanban" ||
                !!callout.querySelector(
                    ".task-kanban-inline-marker, .task-kanban-inline-card"
                ) ||
                /Task Kanban/i.test(callout.textContent || "")
            );
        });

        for (const callout of kanbanCallouts) {
            callout.classList.toggle("is-collapsed", collapsed);
            callout.setAttribute("data-callout-fold", collapsed ? "-" : "+");
            const content = callout.querySelector(".callout-content");
            if (content) {
                content.style.display = collapsed ? "none" : "";
                content.toggleAttribute("hidden", collapsed);
            }
        }
    },

    isTaskKanbanCollapsedInSource() {
        return !!this.element.querySelector(
            ".callout.is-collapsed:has(.task-kanban-inline-marker), .callout[data-callout-fold='-']:has(.task-kanban-inline-marker), .callout.is-collapsed[data-callout='todo'], .callout[data-callout-fold='-'][data-callout='todo'], .callout.is-collapsed[data-callout='task-kanban'], .callout[data-callout-fold='-'][data-callout='task-kanban']"
        );
    },

    async getFullHTML() {
        if (!this.isReadModeActive()) return null;
        return await renderReadMode(this.plugin, this.element);
    },
};

},
"js/minimap-scroll": function(require, module, exports) {
module.exports = {
    getMinimapDragZoneRect() {
        const rect = this.container?.getBoundingClientRect();
        if (!rect) return null;

        const scale = this.yScale || this.scale || 0.12;
        const width = Math.max(1, rect.width * scale);
        return {
            top: rect.top,
            right: rect.right,
            bottom: rect.bottom,
            left: rect.right - width,
            width,
            height: rect.height,
        };
    },

    isPointerInsideMinimapDragZone(event) {
        const rect = this.getMinimapDragZoneRect();
        if (!rect) return false;

        return (
            event.clientX >= rect.left &&
            event.clientX <= rect.right &&
            event.clientY >= rect.top &&
            event.clientY <= rect.bottom
        );
    },

    isPointerInsideMinimapDragColumn(event) {
        const rect = this.getMinimapDragZoneRect();
        if (!rect) return false;

        return event.clientX >= rect.left && event.clientX <= rect.right;
    },

    getSliderVisualHeight() {
        const yScale = this.yScale || this.scale || 1;
        const exactHeight = this.scroller.clientHeight * yScale;
        const zoneWidth = this.getMinimapDragZoneRect()?.width || 0;
        const minHeight = this.yScale < this.scale ? zoneWidth / 2 : 1;
        return Math.max(minHeight, exactHeight, 1);
    },

    getSliderTravelMetrics() {
        const zoneRect = this.getMinimapDragZoneRect();
        const containerRect = this.container.getBoundingClientRect();
        const sliderHeight = this.getSliderVisualHeight();
        const maxScroll = Math.max(
            0,
            this.scroller.scrollHeight - this.scroller.clientHeight
        );
        const topBase = zoneRect.top - containerRect.top;
        const travelHeight = Math.max(0, zoneRect.height - sliderHeight / 2);

        return {
            maxScroll,
            sliderHeight,
            topBase,
            travelHeight,
        };
    },

    updateSliderScroll() {
        if (!this.scroller || !this.yScale || !this.fullHeight) return;
        const scrollTop = this.scroller.scrollTop;
        const topOffset = this.topOffset || 0;
        const effectiveHeight = this.effectiveIframeHeight || this.fullHeight;

        if (scrollTop !== this._lastScrollTop) {
            this._manualMinimapScroll = false;
            this._lastScrollTop = scrollTop;
        }

        const sliderHeight = Math.max(1, this.scroller.clientHeight * this.yScale);
        const editorMaxScroll = Math.max(1, this.scroller.scrollHeight - this.scroller.clientHeight);
        const scrollRatio = scrollTop / editorMaxScroll;

        const BOTTOM_PADDING = 16;
        const rawSliderAbsTop = scrollTop * this.yScale + topOffset;
        const scaledDocHeight = effectiveHeight * this.yScale;
        const maxMinimapScroll = Math.max(0, scaledDocHeight - this.visibleHeight + topOffset);

        if (this._manualMinimapScroll) {
            // independent minimap scroll — just clamp, don't override
            this.minimapScrollTop = Math.max(0, Math.min(this.minimapScrollTop || 0, maxMinimapScroll));
        } else {
            // VSCode auto-follow
            const sliderTargetTop = scrollRatio * (this.visibleHeight - sliderHeight - topOffset - BOTTOM_PADDING);
            this.minimapScrollTop = Math.max(0, Math.min(maxMinimapScroll, rawSliderAbsTop - sliderTargetTop));
        }

        const sliderTop = rawSliderAbsTop - this.minimapScrollTop;

        this.iframe.style.top = `${topOffset - this.minimapScrollTop}px`;
        this.slider.style.height = `${sliderHeight}px`;
        this.slider.style.top = `${sliderTop}px`;
    },

    onSliderMouseDown(event) {
        event.preventDefault();
        this.isDragging = true;
        this.slider.classList.add("dragging");

        const sliderRect = this.slider.getBoundingClientRect();
        this.dragOffsetY = event.clientY - sliderRect.top;

        document.addEventListener("mousemove", this.onSliderMouseMove);
        document.addEventListener("mouseup", this.onSliderMouseUp);
    },

    minimapScrollToY(clientY) {
        if (!this.yScale || !this.scroller) return;
        const rect = this.getMinimapDragZoneRect();
        if (!rect) return;
        const minimapY = (clientY - rect.top) + (this.minimapScrollTop || 0) - (this.topOffset || 0);
        const documentY = minimapY / this.yScale;
        const maxScroll = Math.max(0, this.scroller.scrollHeight - this.scroller.clientHeight);
        this.scroller.scrollTop = Math.max(0, Math.min(maxScroll, documentY - this.scroller.clientHeight / 2));
        this.scroller.dispatchEvent(new Event("scroll"));
        this.updateSliderScroll();
    },

    onMinimapMouseDown(event) {
        if (event.button !== 0 || !this.scroller) return;
        if (
            event.target instanceof Element &&
            event.target.closest(".minimap-slider")
        ) {
            return;
        }
        if (!this.isPointerInsideMinimapDragZone(event)) return;
        event.preventDefault();
        event.stopPropagation();
        this.minimapScrollToY(event.clientY);
        this.isMinimapDragging = true;
        document.addEventListener("mousemove", this.onMinimapDragMove);
        document.addEventListener("mouseup", this.onMinimapDragUp);
    },

    onMinimapDragMove(event) {
        if (!this.isMinimapDragging) return;
        if (!this.isPointerInsideMinimapDragZone(event)) {
            this.onMinimapDragUp();
            return;
        }
        this.minimapScrollToY(event.clientY);
    },

    onMinimapDragUp() {
        this.isMinimapDragging = false;
        document.removeEventListener("mousemove", this.onMinimapDragMove);
        document.removeEventListener("mouseup", this.onMinimapDragUp);
    },

    onMinimapWheel(event) {
        event.preventDefault();
        event.stopPropagation();
        if (!this.yScale || !this.fullHeight) return;
        const delta = event.deltaMode === 1
            ? event.deltaY * 40
            : event.deltaMode === 2
              ? event.deltaY * this.visibleHeight
              : event.deltaY;
        const effectiveHeight = this.effectiveIframeHeight || this.fullHeight;
        const scaledDocHeight = effectiveHeight * this.yScale;
        const maxScroll = Math.max(0, scaledDocHeight - this.visibleHeight + (this.topOffset || 0));
        this.minimapScrollTop = Math.max(0, Math.min(maxScroll, (this.minimapScrollTop || 0) + delta));
        this._manualMinimapScroll = true;
        this.updateSliderScroll();
    },

    onSliderMouseMove(event) {
        if (!this.isDragging) return;
        if (!this.isPointerInsideMinimapDragColumn(event)) {
            this.onSliderMouseUp();
            return;
        }

        const rect = this.container.getBoundingClientRect();
        const sliderTopInContainer = event.clientY - rect.top - this.dragOffsetY;
        const newScrollTop = (sliderTopInContainer + this.minimapScrollTop - (this.topOffset || 0)) / this.yScale;
        const maxScroll = Math.max(0, this.scroller.scrollHeight - this.scroller.clientHeight);
        this.scroller.scrollTop = Math.max(0, Math.min(maxScroll, newScrollTop));
        this.updateSliderScroll();
    },

    onSliderMouseUp() {
        this.isDragging = false;
        this.slider.classList.remove("dragging");
        document.removeEventListener("mousemove", this.onSliderMouseMove);
        document.removeEventListener("mouseup", this.onSliderMouseUp);
    },
};

},
"js/renderers": function(require, module, exports) {
const { MarkdownRenderer, MarkdownView } = require("obsidian");
const { sleep } = require("./utils");

function getMarkdownViewForElement(plugin, sourceElement) {
    const activeView = plugin.app.workspace.getActiveViewOfType(MarkdownView);
    return (
        plugin.app.workspace
            .getLeavesOfType("markdown")
            .map((leaf) => leaf.view)
            .find((view) => view.contentEl === sourceElement) || activeView
    );
}

async function renderMarkdownDocument(plugin, sourceElement) {
    const matchingView = getMarkdownViewForElement(plugin, sourceElement);
    const file = matchingView?.file || plugin.app.workspace.getActiveFile();
    if (!file) return null;

    const noteContent = document.createElement("div");
    noteContent.className = "markdown-reading-view";
    const preview = document.createElement("div");
    preview.className = "markdown-preview-view markdown-rendered";
    const destination = document.createElement("div");
    destination.className = "markdown-preview-sizer markdown-preview-section";
    preview.appendChild(destination);
    noteContent.appendChild(preview);

    const markdown =
        typeof matchingView?.getViewData === "function"
            ? await matchingView.getViewData()
            : await plugin.app.vault.read(file);
    await MarkdownRenderer.render(
        plugin.app,
        markdown,
        destination,
        file.path,
        plugin
    );
    return noteContent;
}

async function renderReadMode(plugin, sourceElement) {
    return await renderMarkdownDocument(plugin, sourceElement);
}

async function renderEditMode(plugin, sourceElement, helperElement, scroller) {
    const renderedDocument = await renderMarkdownDocument(plugin, sourceElement);
    if (renderedDocument) return renderedDocument;

    let noteContent;
    if (helperElement) {
        noteContent = helperElement.cloneNode(true);
    } else {
        const sizer = scroller.firstChild;
        const element = scroller.parentElement.parentElement.parentElement;
        sizer.style = "transform-origin: top right; scale: .1;";
        element.offsetWidth;
        await sleep(10);

        noteContent = element.cloneNode(true);
        sizer.style = "";
    }

    noteContent.querySelectorAll(".cm-sizer").forEach((el) => {
        el.style = "";
    });
    noteContent
        .querySelectorAll(".markdown-source-view > :not(.cm-editor)")
        .forEach((el) => el.remove());

    return noteContent;
}

module.exports = {
    renderEditMode,
    renderReadMode,
};

},
"js/utils": function(require, module, exports) {
function throttle(fn, limit, options = { leading: false, trailing: true }) {
    let inThrottle = false;
    let lastArgs;
    let lastThis;

    const invoke = () => {
        if (lastArgs) {
            fn.apply(lastThis, lastArgs);
            lastArgs = lastThis = null;
            setTimeout(invoke, limit);
        } else {
            inThrottle = false;
        }
    };

    return function (...args) {
        if (!inThrottle) {
            if (options.leading) {
                fn.apply(this, args);
            } else {
                lastArgs = args;
                lastThis = this;
            }
            inThrottle = true;
            setTimeout(invoke, limit);
        } else if (options.trailing) {
            lastArgs = args;
            lastThis = this;
        }
    };
}

function toRGBAAlpha(color, alpha) {
    if (color.startsWith("#")) {
        let hex = color.replace("#", "");
        if (hex.length === 3) {
            hex = hex
                .split("")
                .map((x) => x + x)
                .join("");
        }
        const num = parseInt(hex, 16);
        const r = (num >> 16) & 255;
        const g = (num >> 8) & 255;
        const b = num & 255;
        return `rgba(${r},${g},${b},${alpha})`;
    }

    if (color.startsWith("rgb")) {
        const nums = color.match(/[\d.]+/g);
        if (nums.length >= 3) {
            return `rgba(${nums[0]},${nums[1]},${nums[2]},${alpha})`;
        }
    }

    return color;
}

function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

module.exports = {
    sleep,
    throttle,
    toRGBAAlpha,
};

}
};
const __cache = Object.create(null);
function __normalize(id) {
    const parts = [];
    for (const part of id.split("/")) {
        if (!part || part === ".") continue;
        if (part === "..") parts.pop();
        else parts.push(part);
    }
    return parts.join("/").replace(/\.js$/, "");
}
function __dirnameOf(id) {
    const slash = id.lastIndexOf("/");
    return slash === -1 ? "" : id.slice(0, slash);
}
function __resolve(request, parentId) {
    if (!request.startsWith(".")) return request;
    return __normalize(__dirnameOf(parentId) + "/" + request);
}
function __require(request, parentId) {
    const id = __resolve(request, parentId || "main");
    if (!__modules[id]) return __nativeRequire(request);
    if (__cache[id]) return __cache[id].exports;
    const module = { exports: {} };
    __cache[id] = module;
    const localRequire = (nextRequest) => __require(nextRequest, id);
    __modules[id](localRequire, module, module.exports);
    return module.exports;
}
module.exports = __require("./main", "main");
